services:
  calisto:
    image: calisto
    container_name: calisto:latest

    ports:
      - "3040:3040"

    user: "1000:1000" # Para que no sea root

    volumes:
      - ./data:/app/data

    restart: unless-stopped