spring.application.name=calisto
server.port=3040
spring.mvc.async.request-timeout=-1
logging.file.name=data/logs/calisto.log
logging.logback.rollingpolicy.max-file-size=50MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=5GB